# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "wavetrx"
version = "0.1.0"
edition = "2021"


[dependencies]
hound = "3.5"
rustfft = "6.2"
biquad = "0.3"
cpal = "0.15"


[profile.release]
opt-level = 1
