# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "wavetrx"
version = "0.1.0"
edition = "2021"


[dependencies]
hound = "3.5.0"
rustfft = "6.1.0"
biquad = "0.3.0"


[profile.release]
opt-level = 1
